// Generated by gencpp from file xarm_planner/exec_plan.msg
// DO NOT EDIT!


#ifndef XARM_PLANNER_MESSAGE_EXEC_PLAN_H
#define XARM_PLANNER_MESSAGE_EXEC_PLAN_H

#include <ros/service_traits.h>


#include <xarm_planner/exec_planRequest.h>
#include <xarm_planner/exec_planResponse.h>


namespace xarm_planner
{

struct exec_plan
{

typedef exec_planRequest Request;
typedef exec_planResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct exec_plan
} // namespace xarm_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_planner::exec_plan > {
  static const char* value()
  {
    return "79a98935480e148cf8a7f293507dd090";
  }

  static const char* value(const ::xarm_planner::exec_plan&) { return value(); }
};

template<>
struct DataType< ::xarm_planner::exec_plan > {
  static const char* value()
  {
    return "xarm_planner/exec_plan";
  }

  static const char* value(const ::xarm_planner::exec_plan&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_planner::exec_planRequest> should match
// service_traits::MD5Sum< ::xarm_planner::exec_plan >
template<>
struct MD5Sum< ::xarm_planner::exec_planRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_planner::exec_plan >::value();
  }
  static const char* value(const ::xarm_planner::exec_planRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_planner::exec_planRequest> should match
// service_traits::DataType< ::xarm_planner::exec_plan >
template<>
struct DataType< ::xarm_planner::exec_planRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_planner::exec_plan >::value();
  }
  static const char* value(const ::xarm_planner::exec_planRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_planner::exec_planResponse> should match
// service_traits::MD5Sum< ::xarm_planner::exec_plan >
template<>
struct MD5Sum< ::xarm_planner::exec_planResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_planner::exec_plan >::value();
  }
  static const char* value(const ::xarm_planner::exec_planResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_planner::exec_planResponse> should match
// service_traits::DataType< ::xarm_planner::exec_plan >
template<>
struct DataType< ::xarm_planner::exec_planResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_planner::exec_plan >::value();
  }
  static const char* value(const ::xarm_planner::exec_planResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_PLANNER_MESSAGE_EXEC_PLAN_H
