// Generated by gencpp from file xarm_msgs/Call.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_CALL_H
#define XARM_MSGS_MESSAGE_CALL_H

#include <ros/service_traits.h>


#include <xarm_msgs/CallRequest.h>
#include <xarm_msgs/CallResponse.h>


namespace xarm_msgs
{

struct Call
{

typedef CallRequest Request;
typedef CallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Call
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::Call > {
  static const char* value()
  {
    return "76c68a2c5e109f4d6a4dc1cfc355f405";
  }

  static const char* value(const ::xarm_msgs::Call&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::Call > {
  static const char* value()
  {
    return "xarm_msgs/Call";
  }

  static const char* value(const ::xarm_msgs::Call&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::CallRequest> should match
// service_traits::MD5Sum< ::xarm_msgs::Call >
template<>
struct MD5Sum< ::xarm_msgs::CallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::Call >::value();
  }
  static const char* value(const ::xarm_msgs::CallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::CallRequest> should match
// service_traits::DataType< ::xarm_msgs::Call >
template<>
struct DataType< ::xarm_msgs::CallRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::Call >::value();
  }
  static const char* value(const ::xarm_msgs::CallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::CallResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::Call >
template<>
struct MD5Sum< ::xarm_msgs::CallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::Call >::value();
  }
  static const char* value(const ::xarm_msgs::CallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::CallResponse> should match
// service_traits::DataType< ::xarm_msgs::Call >
template<>
struct DataType< ::xarm_msgs::CallResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::Call >::value();
  }
  static const char* value(const ::xarm_msgs::CallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_CALL_H
