// Generated by gencpp from file xarm_msgs/ClearErr.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_CLEARERR_H
#define XARM_MSGS_MESSAGE_CLEARERR_H

#include <ros/service_traits.h>


#include <xarm_msgs/ClearErrRequest.h>
#include <xarm_msgs/ClearErrResponse.h>


namespace xarm_msgs
{

struct ClearErr
{

typedef ClearErrRequest Request;
typedef ClearErrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearErr
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::ClearErr > {
  static const char* value()
  {
    return "76c68a2c5e109f4d6a4dc1cfc355f405";
  }

  static const char* value(const ::xarm_msgs::ClearErr&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::ClearErr > {
  static const char* value()
  {
    return "xarm_msgs/ClearErr";
  }

  static const char* value(const ::xarm_msgs::ClearErr&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::ClearErrRequest> should match
// service_traits::MD5Sum< ::xarm_msgs::ClearErr >
template<>
struct MD5Sum< ::xarm_msgs::ClearErrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::ClearErr >::value();
  }
  static const char* value(const ::xarm_msgs::ClearErrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::ClearErrRequest> should match
// service_traits::DataType< ::xarm_msgs::ClearErr >
template<>
struct DataType< ::xarm_msgs::ClearErrRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::ClearErr >::value();
  }
  static const char* value(const ::xarm_msgs::ClearErrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::ClearErrResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::ClearErr >
template<>
struct MD5Sum< ::xarm_msgs::ClearErrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::ClearErr >::value();
  }
  static const char* value(const ::xarm_msgs::ClearErrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::ClearErrResponse> should match
// service_traits::DataType< ::xarm_msgs::ClearErr >
template<>
struct DataType< ::xarm_msgs::ClearErrResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::ClearErr >::value();
  }
  static const char* value(const ::xarm_msgs::ClearErrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_CLEARERR_H
