// Generated by gencpp from file xarm_msgs/ConfigToolModbusRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_CONFIGTOOLMODBUSREQUEST_H
#define XARM_MSGS_MESSAGE_CONFIGTOOLMODBUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct ConfigToolModbusRequest_
{
  typedef ConfigToolModbusRequest_<ContainerAllocator> Type;

  ConfigToolModbusRequest_()
    : baud_rate(0)
    , timeout_ms(0)  {
    }
  ConfigToolModbusRequest_(const ContainerAllocator& _alloc)
    : baud_rate(0)
    , timeout_ms(0)  {
  (void)_alloc;
    }



   typedef int32_t _baud_rate_type;
  _baud_rate_type baud_rate;

   typedef int32_t _timeout_ms_type;
  _timeout_ms_type timeout_ms;





  typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigToolModbusRequest_

typedef ::xarm_msgs::ConfigToolModbusRequest_<std::allocator<void> > ConfigToolModbusRequest;

typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusRequest > ConfigToolModbusRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusRequest const> ConfigToolModbusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.baud_rate == rhs.baud_rate &&
    lhs.timeout_ms == rhs.timeout_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e41deb7d5a91bccb5610cc9acda38eb";
  }

  static const char* value(const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e41deb7d5a91bccULL;
  static const uint64_t static_value2 = 0xb5610cc9acda38ebULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/ConfigToolModbusRequest";
  }

  static const char* value(const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# configure the tool modbus communication baud rate, in bps:\n"
"int32 baud_rate\n"
"\n"
"# configure the timeout parameter in modbus communication, in milliseconds\n"
"int32 timeout_ms\n"
"\n"
;
  }

  static const char* value(const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.baud_rate);
      stream.next(m.timeout_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigToolModbusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::ConfigToolModbusRequest_<ContainerAllocator>& v)
  {
    s << indent << "baud_rate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.baud_rate);
    s << indent << "timeout_ms: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timeout_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_CONFIGTOOLMODBUSREQUEST_H
