// Generated by gencpp from file xarm_msgs/ConfigToolModbusResponse.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_CONFIGTOOLMODBUSRESPONSE_H
#define XARM_MSGS_MESSAGE_CONFIGTOOLMODBUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct ConfigToolModbusResponse_
{
  typedef ConfigToolModbusResponse_<ContainerAllocator> Type;

  ConfigToolModbusResponse_()
    : message()
    , ret(0)  {
    }
  ConfigToolModbusResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , ret(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef int16_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigToolModbusResponse_

typedef ::xarm_msgs::ConfigToolModbusResponse_<std::allocator<void> > ConfigToolModbusResponse;

typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusResponse > ConfigToolModbusResponsePtr;
typedef boost::shared_ptr< ::xarm_msgs::ConfigToolModbusResponse const> ConfigToolModbusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator1> & lhs, const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator1> & lhs, const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d61b57e27c330e977d9f6b98b84ff3b";
  }

  static const char* value(const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d61b57e27c330e9ULL;
  static const uint64_t static_value2 = 0x77d9f6b98b84ff3bULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/ConfigToolModbusResponse";
  }

  static const char* value(const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string message\n"
"int16 ret\n"
;
  }

  static const char* value(const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigToolModbusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::ConfigToolModbusResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "ret: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_CONFIGTOOLMODBUSRESPONSE_H
