// Generated by gencpp from file xarm_msgs/GetAnalogIORequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_GETANALOGIOREQUEST_H
#define XARM_MSGS_MESSAGE_GETANALOGIOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct GetAnalogIORequest_
{
  typedef GetAnalogIORequest_<ContainerAllocator> Type;

  GetAnalogIORequest_()
    : port_num(0)  {
    }
  GetAnalogIORequest_(const ContainerAllocator& _alloc)
    : port_num(0)  {
  (void)_alloc;
    }



   typedef int16_t _port_num_type;
  _port_num_type port_num;





  typedef boost::shared_ptr< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetAnalogIORequest_

typedef ::xarm_msgs::GetAnalogIORequest_<std::allocator<void> > GetAnalogIORequest;

typedef boost::shared_ptr< ::xarm_msgs::GetAnalogIORequest > GetAnalogIORequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::GetAnalogIORequest const> GetAnalogIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.port_num == rhs.port_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1c58d245d5dbcbc33afe76f9fc1dff4";
  }

  static const char* value(const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1c58d245d5dbcbcULL;
  static const uint64_t static_value2 = 0x33afe76f9fc1dff4ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/GetAnalogIORequest";
  }

  static const char* value(const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Getting one of the 2 analog Input port at robot end connector or controller\n"
"\n"
"int16 port_num\n"
"\n"
;
  }

  static const char* value(const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAnalogIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::GetAnalogIORequest_<ContainerAllocator>& v)
  {
    s << indent << "port_num: ";
    Printer<int16_t>::stream(s, indent + "  ", v.port_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_GETANALOGIOREQUEST_H
