// Generated by gencpp from file xarm_msgs/GetAnalogIO.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_GETANALOGIO_H
#define XARM_MSGS_MESSAGE_GETANALOGIO_H

#include <ros/service_traits.h>


#include <xarm_msgs/GetAnalogIORequest.h>
#include <xarm_msgs/GetAnalogIOResponse.h>


namespace xarm_msgs
{

struct GetAnalogIO
{

typedef GetAnalogIORequest Request;
typedef GetAnalogIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAnalogIO
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::GetAnalogIO > {
  static const char* value()
  {
    return "be8d9a2c0ed50c727cbf098654568f97";
  }

  static const char* value(const ::xarm_msgs::GetAnalogIO&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::GetAnalogIO > {
  static const char* value()
  {
    return "xarm_msgs/GetAnalogIO";
  }

  static const char* value(const ::xarm_msgs::GetAnalogIO&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::GetAnalogIORequest> should match
// service_traits::MD5Sum< ::xarm_msgs::GetAnalogIO >
template<>
struct MD5Sum< ::xarm_msgs::GetAnalogIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::GetAnalogIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetAnalogIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::GetAnalogIORequest> should match
// service_traits::DataType< ::xarm_msgs::GetAnalogIO >
template<>
struct DataType< ::xarm_msgs::GetAnalogIORequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::GetAnalogIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetAnalogIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::GetAnalogIOResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::GetAnalogIO >
template<>
struct MD5Sum< ::xarm_msgs::GetAnalogIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::GetAnalogIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetAnalogIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::GetAnalogIOResponse> should match
// service_traits::DataType< ::xarm_msgs::GetAnalogIO >
template<>
struct DataType< ::xarm_msgs::GetAnalogIOResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::GetAnalogIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetAnalogIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_GETANALOGIO_H
