// Generated by gencpp from file xarm_msgs/GetControllerDigitalIO.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_GETCONTROLLERDIGITALIO_H
#define XARM_MSGS_MESSAGE_GETCONTROLLERDIGITALIO_H

#include <ros/service_traits.h>


#include <xarm_msgs/GetControllerDigitalIORequest.h>
#include <xarm_msgs/GetControllerDigitalIOResponse.h>


namespace xarm_msgs
{

struct GetControllerDigitalIO
{

typedef GetControllerDigitalIORequest Request;
typedef GetControllerDigitalIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetControllerDigitalIO
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::GetControllerDigitalIO > {
  static const char* value()
  {
    return "a10e26b4b2c853a8b561f9587bff33b2";
  }

  static const char* value(const ::xarm_msgs::GetControllerDigitalIO&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::GetControllerDigitalIO > {
  static const char* value()
  {
    return "xarm_msgs/GetControllerDigitalIO";
  }

  static const char* value(const ::xarm_msgs::GetControllerDigitalIO&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::GetControllerDigitalIORequest> should match
// service_traits::MD5Sum< ::xarm_msgs::GetControllerDigitalIO >
template<>
struct MD5Sum< ::xarm_msgs::GetControllerDigitalIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::GetControllerDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetControllerDigitalIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::GetControllerDigitalIORequest> should match
// service_traits::DataType< ::xarm_msgs::GetControllerDigitalIO >
template<>
struct DataType< ::xarm_msgs::GetControllerDigitalIORequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::GetControllerDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetControllerDigitalIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::GetControllerDigitalIOResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::GetControllerDigitalIO >
template<>
struct MD5Sum< ::xarm_msgs::GetControllerDigitalIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::GetControllerDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetControllerDigitalIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::GetControllerDigitalIOResponse> should match
// service_traits::DataType< ::xarm_msgs::GetControllerDigitalIO >
template<>
struct DataType< ::xarm_msgs::GetControllerDigitalIOResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::GetControllerDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::GetControllerDigitalIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_GETCONTROLLERDIGITALIO_H
