// Generated by gencpp from file xarm_msgs/GetErr.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_GETERR_H
#define XARM_MSGS_MESSAGE_GETERR_H

#include <ros/service_traits.h>


#include <xarm_msgs/GetErrRequest.h>
#include <xarm_msgs/GetErrResponse.h>


namespace xarm_msgs
{

struct GetErr
{

typedef GetErrRequest Request;
typedef GetErrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetErr
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::GetErr > {
  static const char* value()
  {
    return "4d513c3bc98cbaf164b4a46b30ca31f2";
  }

  static const char* value(const ::xarm_msgs::GetErr&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::GetErr > {
  static const char* value()
  {
    return "xarm_msgs/GetErr";
  }

  static const char* value(const ::xarm_msgs::GetErr&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::GetErrRequest> should match
// service_traits::MD5Sum< ::xarm_msgs::GetErr >
template<>
struct MD5Sum< ::xarm_msgs::GetErrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::GetErr >::value();
  }
  static const char* value(const ::xarm_msgs::GetErrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::GetErrRequest> should match
// service_traits::DataType< ::xarm_msgs::GetErr >
template<>
struct DataType< ::xarm_msgs::GetErrRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::GetErr >::value();
  }
  static const char* value(const ::xarm_msgs::GetErrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::GetErrResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::GetErr >
template<>
struct MD5Sum< ::xarm_msgs::GetErrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::GetErr >::value();
  }
  static const char* value(const ::xarm_msgs::GetErrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::GetErrResponse> should match
// service_traits::DataType< ::xarm_msgs::GetErr >
template<>
struct DataType< ::xarm_msgs::GetErrResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::GetErr >::value();
  }
  static const char* value(const ::xarm_msgs::GetErrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_GETERR_H
