// Generated by gencpp from file xarm_msgs/GetInt32Response.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_GETINT32RESPONSE_H
#define XARM_MSGS_MESSAGE_GETINT32RESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct GetInt32Response_
{
  typedef GetInt32Response_<ContainerAllocator> Type;

  GetInt32Response_()
    : data(0)
    , ret(0)
    , message()  {
    }
  GetInt32Response_(const ContainerAllocator& _alloc)
    : data(0)
    , ret(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _data_type;
  _data_type data;

   typedef int16_t _ret_type;
  _ret_type ret;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::xarm_msgs::GetInt32Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::GetInt32Response_<ContainerAllocator> const> ConstPtr;

}; // struct GetInt32Response_

typedef ::xarm_msgs::GetInt32Response_<std::allocator<void> > GetInt32Response;

typedef boost::shared_ptr< ::xarm_msgs::GetInt32Response > GetInt32ResponsePtr;
typedef boost::shared_ptr< ::xarm_msgs::GetInt32Response const> GetInt32ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::GetInt32Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_msgs::GetInt32Response_<ContainerAllocator1> & lhs, const ::xarm_msgs::GetInt32Response_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.ret == rhs.ret &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_msgs::GetInt32Response_<ContainerAllocator1> & lhs, const ::xarm_msgs::GetInt32Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::GetInt32Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::GetInt32Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::GetInt32Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32090468f6dc62f906d83554e3feecc6";
  }

  static const char* value(const ::xarm_msgs::GetInt32Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32090468f6dc62f9ULL;
  static const uint64_t static_value2 = 0x06d83554e3feecc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/GetInt32Response";
  }

  static const char* value(const ::xarm_msgs::GetInt32Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 data\n"
"int16 ret\n"
"string message\n"
;
  }

  static const char* value(const ::xarm_msgs::GetInt32Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.ret);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInt32Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::GetInt32Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::GetInt32Response_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
    s << indent << "ret: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ret);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_GETINT32RESPONSE_H
