// Generated by gencpp from file xarm_msgs/MoveRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_MOVEREQUEST_H
#define XARM_MSGS_MESSAGE_MOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct MoveRequest_
{
  typedef MoveRequest_<ContainerAllocator> Type;

  MoveRequest_()
    : pose()
    , mvvelo(0.0)
    , mvacc(0.0)
    , mvtime(0.0)
    , mvradii(0.0)  {
    }
  MoveRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , mvvelo(0.0)
    , mvacc(0.0)
    , mvtime(0.0)
    , mvradii(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pose_type;
  _pose_type pose;

   typedef float _mvvelo_type;
  _mvvelo_type mvvelo;

   typedef float _mvacc_type;
  _mvacc_type mvacc;

   typedef float _mvtime_type;
  _mvtime_type mvtime;

   typedef float _mvradii_type;
  _mvradii_type mvradii;





  typedef boost::shared_ptr< ::xarm_msgs::MoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::MoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRequest_

typedef ::xarm_msgs::MoveRequest_<std::allocator<void> > MoveRequest;

typedef boost::shared_ptr< ::xarm_msgs::MoveRequest > MoveRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::MoveRequest const> MoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::MoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::MoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_msgs::MoveRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::MoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.mvvelo == rhs.mvvelo &&
    lhs.mvacc == rhs.mvacc &&
    lhs.mvtime == rhs.mvtime &&
    lhs.mvradii == rhs.mvradii;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_msgs::MoveRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::MoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::MoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::MoveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::MoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0e14760ef59968dcef4281098fe75b9";
  }

  static const char* value(const ::xarm_msgs::MoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0e14760ef59968dULL;
  static const uint64_t static_value2 = 0xcef4281098fe75b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/MoveRequest";
  }

  static const char* value(const ::xarm_msgs::MoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request: command specification for motion executions.\n"
"# Units:\n"
"#	joint space/angles: radian, radian/s and radian/s^2.\n"
"#	Cartesian space: mm, mm/s, and mm/s^2.\n"
"#	time: sec\n"
"\n"
"# pose: target coordinate. \n"
"#	For Joint Space target，pose dimention is the number of joints. element as each target joint position.\n"
"#	For Cartesian target: pose dimention is 6 for (x, y, z, roll, pitch, yaw)\n"
"\n"
"float32[] pose\n"
"\n"
"# mvvelo: specified maximum velocity during execution. linear or angular velocity \n"
"\n"
"float32 mvvelo\n"
"\n"
"# mvacc: specified maximum acceleration during execution. linear or angular acceleration.\n"
"\n"
"float32 mvacc\n"
"\n"
"# mvtime: currently do not have any special meaning, please just give it 0. \n"
"# PLEASE NOTE: after firmware version 1.5, For servo_cartesian motion, mvtime will be used as indicator of coordinate system. (0 for BASE coordinate, non-zero for TOOL coordinate)  \n"
"\n"
"float32 mvtime\n"
"\n"
"# mvradii: this is special for move_ineb service, meaning the blending radius between 2 straight path trajectories, 0 for no blend.\n"
"\n"
"float32 mvradii\n"
"\n"
;
  }

  static const char* value(const ::xarm_msgs::MoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.mvvelo);
      stream.next(m.mvacc);
      stream.next(m.mvtime);
      stream.next(m.mvradii);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::MoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::MoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pose[i]);
    }
    s << indent << "mvvelo: ";
    Printer<float>::stream(s, indent + "  ", v.mvvelo);
    s << indent << "mvacc: ";
    Printer<float>::stream(s, indent + "  ", v.mvacc);
    s << indent << "mvtime: ";
    Printer<float>::stream(s, indent + "  ", v.mvtime);
    s << indent << "mvradii: ";
    Printer<float>::stream(s, indent + "  ", v.mvradii);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_MOVEREQUEST_H
