// Generated by gencpp from file xarm_msgs/MoveAxisAngle.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_MOVEAXISANGLE_H
#define XARM_MSGS_MESSAGE_MOVEAXISANGLE_H

#include <ros/service_traits.h>


#include <xarm_msgs/MoveAxisAngleRequest.h>
#include <xarm_msgs/MoveAxisAngleResponse.h>


namespace xarm_msgs
{

struct MoveAxisAngle
{

typedef MoveAxisAngleRequest Request;
typedef MoveAxisAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveAxisAngle
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::MoveAxisAngle > {
  static const char* value()
  {
    return "e3ce015929065df69fd9351b8d2c8407";
  }

  static const char* value(const ::xarm_msgs::MoveAxisAngle&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::MoveAxisAngle > {
  static const char* value()
  {
    return "xarm_msgs/MoveAxisAngle";
  }

  static const char* value(const ::xarm_msgs::MoveAxisAngle&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::MoveAxisAngleRequest> should match
// service_traits::MD5Sum< ::xarm_msgs::MoveAxisAngle >
template<>
struct MD5Sum< ::xarm_msgs::MoveAxisAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::MoveAxisAngle >::value();
  }
  static const char* value(const ::xarm_msgs::MoveAxisAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::MoveAxisAngleRequest> should match
// service_traits::DataType< ::xarm_msgs::MoveAxisAngle >
template<>
struct DataType< ::xarm_msgs::MoveAxisAngleRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::MoveAxisAngle >::value();
  }
  static const char* value(const ::xarm_msgs::MoveAxisAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::MoveAxisAngleResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::MoveAxisAngle >
template<>
struct MD5Sum< ::xarm_msgs::MoveAxisAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::MoveAxisAngle >::value();
  }
  static const char* value(const ::xarm_msgs::MoveAxisAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::MoveAxisAngleResponse> should match
// service_traits::DataType< ::xarm_msgs::MoveAxisAngle >
template<>
struct DataType< ::xarm_msgs::MoveAxisAngleResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::MoveAxisAngle >::value();
  }
  static const char* value(const ::xarm_msgs::MoveAxisAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_MOVEAXISANGLE_H
