// Generated by gencpp from file xarm_msgs/SetDigitalIO.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETDIGITALIO_H
#define XARM_MSGS_MESSAGE_SETDIGITALIO_H

#include <ros/service_traits.h>


#include <xarm_msgs/SetDigitalIORequest.h>
#include <xarm_msgs/SetDigitalIOResponse.h>


namespace xarm_msgs
{

struct SetDigitalIO
{

typedef SetDigitalIORequest Request;
typedef SetDigitalIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDigitalIO
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::SetDigitalIO > {
  static const char* value()
  {
    return "50ac3ff571bfc64bb298f9570217847f";
  }

  static const char* value(const ::xarm_msgs::SetDigitalIO&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::SetDigitalIO > {
  static const char* value()
  {
    return "xarm_msgs/SetDigitalIO";
  }

  static const char* value(const ::xarm_msgs::SetDigitalIO&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::SetDigitalIORequest> should match
// service_traits::MD5Sum< ::xarm_msgs::SetDigitalIO >
template<>
struct MD5Sum< ::xarm_msgs::SetDigitalIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::SetDigitalIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetDigitalIORequest> should match
// service_traits::DataType< ::xarm_msgs::SetDigitalIO >
template<>
struct DataType< ::xarm_msgs::SetDigitalIORequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::SetDigitalIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::SetDigitalIOResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::SetDigitalIO >
template<>
struct MD5Sum< ::xarm_msgs::SetDigitalIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::SetDigitalIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetDigitalIOResponse> should match
// service_traits::DataType< ::xarm_msgs::SetDigitalIO >
template<>
struct DataType< ::xarm_msgs::SetDigitalIOResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetDigitalIO >::value();
  }
  static const char* value(const ::xarm_msgs::SetDigitalIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETDIGITALIO_H
