// Generated by gencpp from file xarm_msgs/SetFloat32.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETFLOAT32_H
#define XARM_MSGS_MESSAGE_SETFLOAT32_H

#include <ros/service_traits.h>


#include <xarm_msgs/SetFloat32Request.h>
#include <xarm_msgs/SetFloat32Response.h>


namespace xarm_msgs
{

struct SetFloat32
{

typedef SetFloat32Request Request;
typedef SetFloat32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat32
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::SetFloat32 > {
  static const char* value()
  {
    return "0eb9eaae8b6c9745e8550d0b1353340c";
  }

  static const char* value(const ::xarm_msgs::SetFloat32&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::SetFloat32 > {
  static const char* value()
  {
    return "xarm_msgs/SetFloat32";
  }

  static const char* value(const ::xarm_msgs::SetFloat32&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::SetFloat32Request> should match
// service_traits::MD5Sum< ::xarm_msgs::SetFloat32 >
template<>
struct MD5Sum< ::xarm_msgs::SetFloat32Request>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::xarm_msgs::SetFloat32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetFloat32Request> should match
// service_traits::DataType< ::xarm_msgs::SetFloat32 >
template<>
struct DataType< ::xarm_msgs::SetFloat32Request>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::xarm_msgs::SetFloat32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::SetFloat32Response> should match
// service_traits::MD5Sum< ::xarm_msgs::SetFloat32 >
template<>
struct MD5Sum< ::xarm_msgs::SetFloat32Response>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::xarm_msgs::SetFloat32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetFloat32Response> should match
// service_traits::DataType< ::xarm_msgs::SetFloat32 >
template<>
struct DataType< ::xarm_msgs::SetFloat32Response>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::xarm_msgs::SetFloat32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETFLOAT32_H
