// Generated by gencpp from file xarm_msgs/SetLoad.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETLOAD_H
#define XARM_MSGS_MESSAGE_SETLOAD_H

#include <ros/service_traits.h>


#include <xarm_msgs/SetLoadRequest.h>
#include <xarm_msgs/SetLoadResponse.h>


namespace xarm_msgs
{

struct SetLoad
{

typedef SetLoadRequest Request;
typedef SetLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLoad
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::SetLoad > {
  static const char* value()
  {
    return "a61cba8401ac162ae54cbe464f360d3c";
  }

  static const char* value(const ::xarm_msgs::SetLoad&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::SetLoad > {
  static const char* value()
  {
    return "xarm_msgs/SetLoad";
  }

  static const char* value(const ::xarm_msgs::SetLoad&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::SetLoadRequest> should match
// service_traits::MD5Sum< ::xarm_msgs::SetLoad >
template<>
struct MD5Sum< ::xarm_msgs::SetLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetLoad >::value();
  }
  static const char* value(const ::xarm_msgs::SetLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetLoadRequest> should match
// service_traits::DataType< ::xarm_msgs::SetLoad >
template<>
struct DataType< ::xarm_msgs::SetLoadRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetLoad >::value();
  }
  static const char* value(const ::xarm_msgs::SetLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::SetLoadResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::SetLoad >
template<>
struct MD5Sum< ::xarm_msgs::SetLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetLoad >::value();
  }
  static const char* value(const ::xarm_msgs::SetLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetLoadResponse> should match
// service_traits::DataType< ::xarm_msgs::SetLoad >
template<>
struct DataType< ::xarm_msgs::SetLoadResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetLoad >::value();
  }
  static const char* value(const ::xarm_msgs::SetLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETLOAD_H
