// Generated by gencpp from file xarm_msgs/SetModbusTimeout.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETMODBUSTIMEOUT_H
#define XARM_MSGS_MESSAGE_SETMODBUSTIMEOUT_H

#include <ros/service_traits.h>


#include <xarm_msgs/SetModbusTimeoutRequest.h>
#include <xarm_msgs/SetModbusTimeoutResponse.h>


namespace xarm_msgs
{

struct SetModbusTimeout
{

typedef SetModbusTimeoutRequest Request;
typedef SetModbusTimeoutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetModbusTimeout
} // namespace xarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_msgs::SetModbusTimeout > {
  static const char* value()
  {
    return "cd53862105e4494b607dc1eaae204c5f";
  }

  static const char* value(const ::xarm_msgs::SetModbusTimeout&) { return value(); }
};

template<>
struct DataType< ::xarm_msgs::SetModbusTimeout > {
  static const char* value()
  {
    return "xarm_msgs/SetModbusTimeout";
  }

  static const char* value(const ::xarm_msgs::SetModbusTimeout&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_msgs::SetModbusTimeoutRequest> should match
// service_traits::MD5Sum< ::xarm_msgs::SetModbusTimeout >
template<>
struct MD5Sum< ::xarm_msgs::SetModbusTimeoutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetModbusTimeout >::value();
  }
  static const char* value(const ::xarm_msgs::SetModbusTimeoutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetModbusTimeoutRequest> should match
// service_traits::DataType< ::xarm_msgs::SetModbusTimeout >
template<>
struct DataType< ::xarm_msgs::SetModbusTimeoutRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetModbusTimeout >::value();
  }
  static const char* value(const ::xarm_msgs::SetModbusTimeoutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_msgs::SetModbusTimeoutResponse> should match
// service_traits::MD5Sum< ::xarm_msgs::SetModbusTimeout >
template<>
struct MD5Sum< ::xarm_msgs::SetModbusTimeoutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_msgs::SetModbusTimeout >::value();
  }
  static const char* value(const ::xarm_msgs::SetModbusTimeoutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_msgs::SetModbusTimeoutResponse> should match
// service_traits::DataType< ::xarm_msgs::SetModbusTimeout >
template<>
struct DataType< ::xarm_msgs::SetModbusTimeoutResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_msgs::SetModbusTimeout >::value();
  }
  static const char* value(const ::xarm_msgs::SetModbusTimeoutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETMODBUSTIMEOUT_H
