// Generated by gencpp from file xarm_msgs/SetMultipleIntsRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETMULTIPLEINTSREQUEST_H
#define XARM_MSGS_MESSAGE_SETMULTIPLEINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct SetMultipleIntsRequest_
{
  typedef SetMultipleIntsRequest_<ContainerAllocator> Type;

  SetMultipleIntsRequest_()
    : data_int()  {
    }
  SetMultipleIntsRequest_(const ContainerAllocator& _alloc)
    : data_int(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_int_type;
  _data_int_type data_int;





  typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMultipleIntsRequest_

typedef ::xarm_msgs::SetMultipleIntsRequest_<std::allocator<void> > SetMultipleIntsRequest;

typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest > SetMultipleIntsRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest const> SetMultipleIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data_int == rhs.data_int;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44acdf287a0679e58f3ebc0c5712b826";
  }

  static const char* value(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44acdf287a0679e5ULL;
  static const uint64_t static_value2 = 0x8f3ebc0c5712b826ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/SetMultipleIntsRequest";
  }

  static const char* value(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request: set multiple integer parameters.\n"
"# data_int: int values to be set.\n"
"\n"
"int16[] data_int\n"
"\n"
;
  }

  static const char* value(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMultipleIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "data_int[]" << std::endl;
    for (size_t i = 0; i < v.data_int.size(); ++i)
    {
      s << indent << "  data_int[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data_int[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETMULTIPLEINTSREQUEST_H
