// Generated by gencpp from file xarm_msgs/SetToolModbusRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETTOOLMODBUSREQUEST_H
#define XARM_MSGS_MESSAGE_SETTOOLMODBUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct SetToolModbusRequest_
{
  typedef SetToolModbusRequest_<ContainerAllocator> Type;

  SetToolModbusRequest_()
    : send_data()
    , respond_len(0)  {
    }
  SetToolModbusRequest_(const ContainerAllocator& _alloc)
    : send_data(_alloc)
    , respond_len(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _send_data_type;
  _send_data_type send_data;

   typedef int16_t _respond_len_type;
  _respond_len_type respond_len;





  typedef boost::shared_ptr< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetToolModbusRequest_

typedef ::xarm_msgs::SetToolModbusRequest_<std::allocator<void> > SetToolModbusRequest;

typedef boost::shared_ptr< ::xarm_msgs::SetToolModbusRequest > SetToolModbusRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::SetToolModbusRequest const> SetToolModbusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.send_data == rhs.send_data &&
    lhs.respond_len == rhs.respond_len;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator1> & lhs, const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "199c3425393f03db695077c48d89982d";
  }

  static const char* value(const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x199c3425393f03dbULL;
  static const uint64_t static_value2 = 0x695077c48d89982dULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/SetToolModbusRequest";
  }

  static const char* value(const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# unsigned char data to be sent to tool device through modbus\n"
"uint8[] send_data\n"
"\n"
"# Specify the anticipated maximum respond data length in bytes\n"
"int16 respond_len\n"
"\n"
;
  }

  static const char* value(const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.send_data);
      stream.next(m.respond_len);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetToolModbusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::SetToolModbusRequest_<ContainerAllocator>& v)
  {
    s << indent << "send_data[]" << std::endl;
    for (size_t i = 0; i < v.send_data.size(); ++i)
    {
      s << indent << "  send_data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.send_data[i]);
    }
    s << indent << "respond_len: ";
    Printer<int16_t>::stream(s, indent + "  ", v.respond_len);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETTOOLMODBUSREQUEST_H
